[pytest]
# addopts = --create-db
# addopts = --cov --cov-report=html
# -- recommended but optional:
python_files = tests.py test_*.py *_tests.py tests_*.py
filterwarnings =
    ignore:Unverified HTTPS request
