HUB_USERNAME = "ubidots"
ARGO_VERSION = "2.1.0"
ARGO_IMAGE_NAME = f"{HUB_USERNAME}/functions-argo:{ARGO_VERSION}"

ARGO_CONTAINER_NAME = "argo"
ARGO_LABEL_KEY = "ubidots_cli_argo"
ARGO_HOSTNAME = "ubi.argo"
ARGO_API_BASE_PATH = "api/_/route"
ARGO_INTERNAL_ADAPTER_PORT = "8040/tcp"
ARGO_INTERNAL_TARGET_PORT = "8042/tcp"
ARGO_EXTERNAL_ADAPTER_PORT = 8040
ARGO_EXTERNAL_TARGET_PORT = 8042
HOST_BIND = "127.0.0.1"
